### ISSUE TITLE
GA: Create method in GA class to accept file output path

### ISSUE THREAD

**Issue by frantic0** [frantic0/genam#2]
model.setPath('/SAN/uclic/ammdgop/data')

**Comment by PrateekM01** [comment]
Designated paths have been added to store the final_results.out file.

**Comment by frantic0** [comment]
we want to pass the path to a designated file in CSV format that lists all the previously generated individuals.

This should be done with an instance (GA) method, like

model.setPath('PATH/individuals.csv')

Each individual should be structured with bricks IDs, optimisation value, individual ID, generation ID.

**Comment by PrateekM01** [comment]
Resolved. Please see the commits done on June 22, 2022
