### ISSUE TITLE
GA: Prevent individuals of past generations from being evaluated in future generations

### ISSUE THREAD

**Issue by frantic0** [frantic0/genam#4]
We want to make our GA optimisation efficient and prevent unnecessary evaluation/generation of repeated individual, mostly because it is expensive.

We probably want to maintain a cache of individuals in the run time and read from the output file which individuals have been generated before and use that to prevent.

**Comment by PrateekM01** [comment]
It has been addressed. 
Now every new individual will be generated without any repetition.

**Comment by frantic0** [comment]
for each execution of the GA, maintain a data structure with individuals/generations in the run time. 

in the first execution, as you create each individual, add it to the structure and write it to a newly created CSV file ((passed in mode.addPath(PATH))

in a given execution, if there is already a file (passed in mode.addPath(PATH)), build your data structure of past individuals/generations from the data parsed from the CSV file. 

This data structure should be looked up each time a new individual is created to ensure it is dissimilar to a previously generated individual.

**Comment by PrateekM01** [comment]
Resolved. Please see the commit on June 22, 2022

**Comment by frantic0** [comment]
not yet...

_"in the first execution, as you create each individual, add it to the structure and write it to a newly created CSV file ((passed in mode.addPath(PATH))"_

to be clear, we need to keep the CSV up-to-date (ideally after each individual's generation, not just after each generation) so that GA does not re-generate past individuals. 

If the process running GA suddenly interrupts — e.g. in case a cluster job with limited time budget runs out of budget or some power failure hazard – before finishing the number of generations that were parameterised, we want to be able to start a new process that picks up the optimisation process, loads the generations/individuals history and carries on efficiently.

**Comment by PrateekM01** [comment]
It's done !!  

Irrespective of where the code will be stopped, the process can continue from the next generation. 
There will be no repetition, and different combinations of the same ids will be created as it was removed earlier 
CSV file will be updated after every generation so you can see the values after each generation. 

To make it more user-friendly, iteration number and population size are defined in the main file (test_close_loop_opitmization.py), so now users can change them freely as per their requirement. 

Check new update - July 3, 2022
